# build with
# ansible-builder build --tag lfops_ee:local -vvv
# takes around 3 mins

# https://ansible.readthedocs.io/projects/builder/en/stable/definition/#builder-ee-definition
version: 3

images:
  base_image:
    name: 'quay.io/rockylinux/rockylinux:9'

dependencies:
  ansible_runner:
    package_pip: 'ansible-runner'

  ansible_core:
    package_pip: 'ansible-core>=2.16.0,<2.17.0' # make sure the ansible version works with rhel8

  galaxy: 'execution-environment-requirements.yml'

  python:
    - 'passlib' # required for ansible.builtin.password_hash filter

  python_interpreter:
    package_system: 'python3.11'
    python_path: '/usr/bin/python3.11'

  system:
    - 'git-core' # required for ansible.builtin.git module

additional_build_files:
  - src: 'linuxfabrik-lfops.tar.gz'
    dest: '.'
