name: 'Linuxfabrik: Release'

on:
  workflow_dispatch: # yamllint disable-line rule:empty-values

# modify the default permissions granted to the GITHUB_TOKEN
permissions:
  contents: 'write' # to push to the repo and create the release

jobs:
  release:
    runs-on: 'ubuntu-latest'

    steps:

      - name: 'git clone https://github.com/Linuxfabrik/THIS-REPO'
        uses: 'actions/checkout@v4'

      - name: 'Fetch the current version from Github'
        run: 'build/get-latest-version.sh'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: 'Create git tag'
        run: |
          # strip the last .123 to for semver compatibility
          VERSION="${LFOPS_VERSION%.*}"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

          git config user.name "github-actions"
          git config user.email "actions@github.com"

          git tag "v$VERSION"
          git push --tags

      - name: 'Create GitHub Release'
        uses: 'softprops/action-gh-release@v2'
        with:
          tag_name: 'v${{ env.VERSION }}'
          body: |
            Release Notes/CHANGELOG at https://github.com/Linuxfabrik/lfops/blob/main/CHANGELOG.md
          prerelease: false
